### ISSUE TITLE
Nightly releases on Pypi are failing

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2373]
## 🐛 Bug description

https://github.com/pytorch/ignite/runs/4576936077?check_suite_focus=true

- build and publish PyPi binaries
```
 removing build/bdist.linux-x86_64/wheel
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/__main__.py", line 28, in main
    result = cli.dispatch(sys.argv[1:])
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/cli.py", line 71, in dispatch
    return main(args.args)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/commands/check.py", line 191, in main
    return check(parsed_args.dists, strict=parsed_args.strict)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/commands/check.py", line 135, in check
    warnings, is_ok = _check_file(filename, render_warning_stream)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/commands/check.py", line 80, in _check_file
    metadata = package.metadata_dictionary()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/package.py", line 175, in metadata_dictionary
    "dynamic": meta.dynamic,
AttributeError: 'Wheel' object has no attribute 'dynamic'
Checking dist/pytorch_ignite-0.5.0.dev20211220-py3-none-any.whl: 
```

- create issue if workflow failed (=> fixed on master by #2374 )
```
Run JasonEtco/create-an-issue@v2
✖  fatal     The following secrets are required for this GitHub Action to run:
- GITHUB_TOKEN
```

cc @trsvchn @ydcjeff

**Comment by vfdev-5** [comment]
Issue is related to pkginfo version and the way how conda envs work.
- Step "Install dependencies" installs pkginfo==1.8.2 which is ok and should work
- Step "Build and Publish Conda binaries" and the command `conda install -y conda-build conda-verify anaconda-client` install pkginfo==1.7.1 which incompatible. 
- twine reports using 1.8.2 and even `conda list | grep pkginfo` shows 1.8.2 but `python -m twine check dist/*` fails with `AttributeError: 'Wheel' object has no attribute 'dynamic'`

```
(test) # conda list | grep pkginfo
pkginfo                   1.8.2                    pypi_0    pypi

(test) # pip list | grep pkginfo
pkginfo                       1.8.2

(test) # which twine
/opt/conda/envs/test/bin/twine

(test) # twine --version
twine version 3.7.1 (importlib_metadata: 4.10.0, pkginfo: 1.7.1, requests: 2.26.0, requests-toolbelt: 0.9.1, tqdm: 4.62.3)
```
