### PR TITLE
Try to fix nightly pypi release

### LINKED ISSUE #2373: Nightly releases on Pypi are failing
## 🐛 Bug description

https://github.com/pytorch/ignite/runs/4576936077?check_suite_focus=true

- build and publish PyPi binaries
```
 removing build/bdist.linux-x86_64/wheel
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/__main__.py", line 28, in main
    result = cli.dispatch(sys.argv[1:])
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/cli.py", line 71, in dispatch
    return main(args.args)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/commands/check.py", line 191, in main
    return check(parsed_args.dists, strict=parsed_args.strict)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/commands/check.py", line 135, in check
    warnings, is_ok = _check_file(filename, render_warning_stream)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/commands/check.py", line 80, in _check_file
    metadata = package.metadata_dictionary()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/twine/package.py", line 175, in metadata_dictionary
    "dynamic": meta.dynamic,
AttributeError: 'Wheel' object has no attribute 'dynamic'
Checking dist/pytorch_ignite-0.5.0.dev20211220-py3-none-any.whl: 
```

- create issue if workflow failed (=> fixed on master by #2374 )
```
Run JasonEtco/create-an-issue@v2
✖  fatal     The following secrets are required for this GitHub Action to run:
- GITHUB_TOKEN
```

cc @trsvchn @ydcjeff

### PR DESCRIPTION
**Pull request by vfdev-5**
Fixes #2373 

Description:
- moved twine installation to pypi related step

Note:
- https://github.com/pypa/twine/issues/846#issuecomment-998409449

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

**Review by trsvchn — APPROVED** [review]
Thanks a lot @vfdev-5 ! LGTM!
